"""
ML Model wrapper for the SAVE Engine.
Trains a RandomForestClassifier on synthetic simulation data generated by
the SAVESimulator, then exposes a predict_proba interface for app.py.
"""
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler


def _generate_training_data(n_normal: int = 2000, n_attack: int = 400,
                             random_state: int = 42) -> pd.DataFrame:
    """
    Generates a synthetic labeled dataset without running the full SAVE pipeline.
    Features are sampled from distributions that reflect genuine vs. attack behavior.
    """
    rng = np.random.default_rng(random_state)

    # --- Normal transactions ---
    normal = pd.DataFrame({
        "drift":          rng.uniform(0.0, 0.4, n_normal),
        "preamble_score": rng.choice([0.1, 0.7], n_normal, p=[0.85, 0.15]),
        "vel_penalty":    rng.choice([1.0, 2.0], n_normal, p=[0.90, 0.10]),
        "amount_risk":    rng.uniform(0.0, 0.3, n_normal),
        "p_model":        rng.uniform(0.01, 0.20, n_normal),
        "is_attack":      False,
    })

    # --- Attack transactions ---
    attack = pd.DataFrame({
        "drift":          rng.uniform(0.5, 1.0, n_attack),
        "preamble_score": rng.choice([0.9, 0.7], n_attack, p=[0.80, 0.20]),
        "vel_penalty":    rng.choice([2.0, 3.0], n_attack, p=[0.60, 0.40]),
        "amount_risk":    rng.uniform(0.5, 1.0, n_attack),
        "p_model":        rng.uniform(0.70, 0.95, n_attack),
        "is_attack":      True,
    })

    return pd.concat([normal, attack], ignore_index=True).sample(
        frac=1, random_state=random_state
    )


FEATURE_COLS = ["drift", "preamble_score", "vel_penalty", "amount_risk"]


class SAVEModel:
    """
    Thin wrapper around a sklearn RandomForest trained on synthetic SAVE data.
    Replaces the hardcoded p_model heuristic in the original app.
    """

    def __init__(self):
        self._model = RandomForestClassifier(
            n_estimators=120,
            max_depth=8,
            random_state=42,
            class_weight="balanced",
        )
        self._scaler = StandardScaler()
        self._trained = False

    def train(self):
        df = _generate_training_data()
        X = df[FEATURE_COLS].values
        y = df["is_attack"].astype(int).values

        X_scaled = self._scaler.fit_transform(X)
        self._model.fit(X_scaled, y)
        self._trained = True

    def predict_proba(self, drift: float, preamble_score: float,
                      vel_penalty: float, amount_risk: float) -> float:
        """Returns P(attack) in [0, 1]."""
        if not self._trained:
            self.train()
        X = np.array([[drift, preamble_score, vel_penalty, amount_risk]])
        X_scaled = self._scaler.transform(X)
        return float(self._model.predict_proba(X_scaled)[0][1])

    def feature_importances(self) -> dict:
        if not self._trained:
            self.train()
        return dict(zip(FEATURE_COLS, self._model.feature_importances_.tolist()))
